version: "3"
services:
  postgres:
    image: postgres:16-alpine
    container_name: airlineservice-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  airlineservice-api:
    image: acmesky-airlineservice-api
    container_name: airlineservice-api
    networks:
      - default
      - acmesky
    environment:
      - DATABASE_DSN=${DATABASE_DSN}
      - JWT_TOKEN=${JWT_TOKEN}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  acmesky:
    external: true
